# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{isolate-scenarios}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Nichols"]
  s.date = %q{2010-07-01}
  s.default_executable = %q{isolate-scenarios}
  s.description = %q{Tool for testing libraries using different senarios of gem versions}
  s.email = %q{josh@technicalpickles.com}
  s.executables = ["isolate-scenarios"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "IsolateScenarios",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "bin/isolate-scenarios",
     "isolate-scenarios.gemspec",
     "lib/isolate-scenarios.rb",
     "lib/isolate/scenarios.rb",
     "lib/isolate/scenarios/cli.rb",
     "lib/isolate/scenarios/now.rb",
     "lib/isolate/scenarios/sandbox.rb",
     "spec/isolate-scenarios_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/technicalpickles/isolate-scenarios}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Tool for testing libraries using different senarios of gem versions}
  s.test_files = [
    "spec/isolate-scenarios_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

